export default [
    'other', 'tập đoàn vingroup', 'tân hoàng minh group',
    'tổng công ty đầu tư phát triển hạ tầng đô thị - udic',
    'công ty tnhh thương mại - quảng cáo - xây dựng - địa ốc việt hân',
    'công ty cp xây dựng số 2 - vinaconex2',
    'công ty cp xuất nhập khẩu tổng hợp hà nội - geleximco',
    'công ty cp tập đoàn sunshine', 'công ty cổ phần tập đoàn flc',
    'công ty cp xây dựng và thương mại bắc hà',
    'công ty tnhh phát triển khu đô thị nam thăng long',
    'công ty cp tập đoàn nam cường hà nội',
    'công ty cp đầu tư văn phú - invest',
    'công ty cp đầu tư xây dựng số 9 hà nội',
    'tổng công ty đầu tư và phát triển nhà hà nội - handico',
    'doanh nghiệp tư nhân xây dựng số 1 tỉnh điện biên',
    'tổng công ty đầu tư phát triển nhà và đô thị bộ quốc phòng',
    'công ty cp sông đà 7',
    'tổng công ty đầu tư phát triển nhà và đô thị hud',
    'công ty tnhh bất động sản và xây dựng việt hưng',
    'tập đoàn sun group', 'công ty cổ phần đầu tư mai linh',
    'tập đoàn hòa phát', 'công ty cp terra gold việt nam',
    'công ty cp đầu tư phú thượng ', 'công ty cp đầu tư hải phát',
    'tổng công ty 319 - bộ quốc phòng',
    'tổng công ty cp thương mại xây dựng',
    'công ty cp đầu tư xây dựng phát triển nhà số 7 hà nội ',
    'công ty cp y dược phẩm vimedimex', 'tập đoàn brg',
    'công ty cp tập đoàn s.s.g', 'tổng công ty 36 - bộ quốc phòng',
    'công ty cp hóa dầu quân đội',
    'tổng công ty đầu tư và phát triển nhà hà nội (handico)',
    'công ty cp đầu tư và thương mại thăng long',
    'tổng công ty viglacera',
    'công ty cp đầu tư kinh doanh và phát triển hạ tầng kcn phúc hà',
    'công ty cp đầu tư hải phát thủ đô',
    'công ty cp đầu tư bất động sản đông đô - bqp',
    'công ty tsq việt nam',
    'công ty cp đầu tư xây dựng và kinh doanh nhà hà nội số 35',
    'tổng công ty cp xuất nhập khẩu và xây dựng việt nam',
    'công ty cp đầu tư hạ tầng và công trình kiến trúc hà nội',
    'công ty cp tập đoàn xây dựng và thiết bị công nghiệp cie corp',
    'tổng công ty đầu tư phát triển nhà và đô thị bộ quốc phòng ',
    'công ty tnhh thiên hương',
    'công ty cp đầu tư và phát triển đô thị long giang',
    'công ty cp đầu tư bất động sản toàn cầu (gp invest)',
    'công ty cp sông đà thăng long',
    'công ty tnhh mtv đầu tư phương đông',
    'công ty tnhh gamuda land việt nam', 'hd mon holdings',
    'công ty cp đầu tư phát triển đô thị và kcn sông đà - sudico',
    'công ty tnhh đầu tư bất động sản dlc',
    'công ty cp ngôi sao an bình', 'công ty cp xây dựng số 1 hà nội',
    'công ty cp bất động sản hải phát',
    'công ty cp xây dựng và phát triển hạ tầng đô thị - bid việt nam',
    'công ty cp xây dựng số 3 - vinaconex3',
    'công ty tnhh bánh kẹo thăng long',
    'công ty cp đầu tư và xây dựng xuân mai',
    'công ty cp đầu tư xây dựng hạ tầng và giao thông',
    'công ty cp đầu tư và thương mại thủ đô',
    'công ty tnhh 19-12 bắc hà', 'tập đoàn capitaland',
    'xí nghiệp xây dựng tư nhân số 1 lai châu',
    'công ty cp đầu tư và xây dựng hud1', 'công ty tnhh hanotex',
    'tập đoàn bitexco', 'tổng công ty xây dựng hà nội',
    'tập đoàn tecco', 'công ty cp phát triển tài trợ  địa ốc r.c',
    'công ty đầu tư xây dựng số 2 hà nội', 'công ty booyoung',
    'công ty cổ phần địa ốc mb',
    'công ty cp xây dựng và kỹ thuật việt nam ',
    'công ty cp đầu tư hải đăng',
    'công ty cp đầu tư và phát triển hòa bình - hbi',
    'công ty tnhh indochina land', 'công ty cp hoa anh đào',
    'tập đoàn keangnam enterprise', 'công ty cp vinaconex 21',
    'công ty cp xây dựng công nghiệp icc',
    'công ty cp đầu tư dịch vụ tài chính hoàng huy',
    'công ty cp đầu tư - thiết kế và xây dựng việt nam',
    'công ty cp eurowindow holding', 'công ty cp đại việt trí tuệ',
    'công ty cp xây dựng phục hưng holdings', 'công ty cp tid',
    'công ty cp xây lắp điện 1', 'công ty cp vimeco',
    'công ty cp eco land', 'công ty cp tập đoàn t&t',
    'công ty cp đầu tư xây dựng nhs',
    'công ty liên doanh hà việt – tungshing', 'tập đoàn mường thanh',
    'công ty tnhh xuân phương', 'công ty cp nông sản agrexim',
    'công ty cp bất động sản hanovid'
]